<a href="https://colab.research.google.com/github/cristiancamiloosoriohernandez/Taller-2---Pandas/blob/main/Taller%202%20-%20PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LIMPIEZA Y TRANSFORMACIÒN DE DATOS

Instrucciones:

Formula al menos 3 preguntas de análisis sobre tu conjunto de datos.luego utilizando Pandas:

1.Limpieza de datos (Pandas: dropna, fillna, replace, etc.)

2.Filtrado y selección de datos

3.Transformación de columnas, creación de variables nuevas

4.Agrupaciones y resúmenes (groupby)

5.Responde las preguntas planteadas con una breve interpretación.

In [ ]:
import pandas as pd
df_mundial = pd.read_csv(r"/content/WorldCupMatches-selected-columns.csv")
df_mundial.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,

In [ ]:
df_mundial.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1074 entries, 0 to 1073
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             1074 non-null   float64
 1   Datetime         980 non-null    object
 2   Stage            1074 non-null   object
 3   Stadium          1074 non-null   object
 4   City             1074 non-null   object
 5   Home Team Name   1074 non-null   object
 6   Home Team Goals  1074 non-null   float64
 7   Away Team Goals  1074 non-null   float64
 8   Away Team Name   1074 non-null   object
 9   Win conditions   1074 non-null   object
dtypes: float64(3), object(7)
memory usage: 84.0+ KB

Eliminación de duplicados

In [ ]:
df_mundial.duplicated().sum()

np.int64(16)

In [ ]:
df_mundial[df_mundial.duplicated(keep=False)]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions
820,2014.0,28 Jun 2014 - 13:00,Round of 16,Estadio Mineirao,Belo Horizonte,Brazil,1.0,1.0,Chile,Brazil win on penalties (3 - 2)
821,2014.0,28 Jun 2014 - 17:00,Round of 16,Estadio do Maracana,Rio De Janeiro,Colombia,2.0,0.0,Uruguay,
822,2014.0,30 Jun 2014 - 13:00,Round of 16,Estadio Nacional,Brasilia,France,2.0,0.0,Nigeria,
823,2014.0,30 Jun 2014 - 17:00,Round of 16,Estadio Beira-Rio,Porto Alegre,Germany,2.0,1.0,Algeria,Germany win after extra time
824,2014.0,04 Jul 2014 - 17:00,Quarter-finals,Estadio Castelao,Fortaleza,Brazil,2.0,1.0,Colombia,
825,2014.0,04 Jul 2014 - 13:00,Quarter-finals,Estadio do Maracana,Rio De Janeiro,France,0.0,1.0,Germany,
826,2014.0,08 Jul 2014 - 17:00,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1.0,7.0,Germany,
827,2014.0,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0.0,3.0,Netherlands,
828,2014.0,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1.0,0.0,Argentina,Germany win after extra time
829,2014.0,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0.0,0.0,Argentina,Argentina win on penalties (2 - 4)
830,2014.0,05 Jul 2014 - 17:00,Quarter-finals,Arena Fonte Nova,Salvador,Netherlands,0.0,0.0,Costa Rica,Netherlands win on penalties (4 - 3)
831,2014.0,05 Jul 2014 - 13:00,Quarter-finals,Estadio Nacional,Brasilia,Argentina,1.0,0.0,Belgium,
832,2014.0,29 Jun 2014 - 13:00,Round of 16,Estadio Castelao,Fortaleza,Netherlands,2.0,1.0,Mexico,
833,2014.0,29 Jun 2014 - 17:00,Round of 16,Arena Pernambuco,Recife,Costa Rica,1.0,1.0,Greece,Costa Rica win on penalties (5 - 3)
834,2014.0,01 Jul 2014 - 13:00,Round of 16,Arena de Sao Paulo,Sao Paulo,Argentina,1.0,0.0,Switzerland,Argentina win after extra time
835,2014.0,01 Jul 2014 - 17:00,Round of 16,Arena Fonte Nova,Salvador,Belgium,2.0,1.0,USA,Belgium win after extra time
836,2014.0,28 Jun 2014 - 13:00,Round of 16,Estadio Mineirao,Belo Horizonte,Brazil,1.0,1.0,Chile,Brazil win on penalties (3 - 2)
837,2014.0,28 Jun 2014 - 17:00,Round of 16,Estadio do Maracana,Rio De Janeiro,Colombia,2.0,0.0,Uruguay,
838,2014.0,29 Jun 2014 - 13:00,Round of 16,Estadio Castelao,Fortaleza,Netherlands,2.0,1.0,Mexico,
839,2014.0,29 Jun 2014 - 17:00,Round of 16,Arena Pernambuco,Recife,Costa Rica,1.0,1.0,Greece,Costa Rica win on penalties (5 - 3)
840,2014.0,30 Jun 2014 - 13:00,Round of 16,Estadio Nacional,Brasilia,France,2.0,0.0,Nigeria,
841,2014.0,30 Jun 2014 - 17:00,Round of 16,Estadio Beira-Rio,Porto Alegre,Germany,2.0,1.0,Algeria,Germany win after extra time
842,2014.0,01 Jul 2014 - 13:00,Round of 16,Arena de Sao Paulo,Sao Paulo,Argentina,1.0,0.0,Switzerland,Argentina win after extra time
843,2014.0,01 Jul 2014 - 17:00,Round of 16,Arena Fonte Nova,Salvador,Belgium,2.0,1.0,USA,Belgium win after extra time
844,2014.0,04 Jul 2014 - 13:00,Quarter-finals,Estadio do Maracana,Rio De Janeiro,France,0.0,1.0,Germany,
845,2014.0,04 Jul 2014 - 17:00,Quarter-finals,Estadio Castelao,Fortaleza,Brazil,2.0,1.0,Colombia,
846,2014.0,05 Jul 2014 - 13:00,Quarter-finals,Estadio Nacional,Brasilia,Argentina,1.0,0.0,Belgium,
847,2014.0,05 Jul 2014 - 17:00,Quarter-finals,Arena Fonte Nova,Salvador,Netherlands,0.0,0.0,Costa Rica,Netherlands win on penalties (4 - 3)
848,2014.0,08 Jul 2014 - 17:00,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1.0,7.0,Germany,
849,2014.0,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0.0,0.0,Argentina,Argentina win on penalties (2 - 4)
850,2014.0,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0.0,3.0,Netherlands,
851,2014.0,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1.0,0.0,Argentina,Germany win after extra time

In [ ]:
df_mundial.drop_duplicates(inplace=True, keep="first")
df_mundial.duplicated().sum()

np.int64(0)

In [ ]:
df_mundial = df_mundial.reset_index(drop=True)
df_mundial.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,

Limpieza datos numericos

In [ ]:
df_mundial["Datetime"] = pd.to_datetime(df_mundial["Datetime"], errors="coerce")
df_mundial.info()
df_mundial.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1058 entries, 0 to 1057
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             1058 non-null   float64
 1   Datetime         826 non-null    datetime64[ns]
 2   Stage            1058 non-null   object
 3   Stadium          1058 non-null   object
 4   City             1058 non-null   object
 5   Home Team Name   1058 non-null   object
 6   Home Team Goals  1058 non-null   float64
 7   Away Team Goals  1058 non-null   float64
 8   Away Team Name   1058 non-null   object
 9   Win conditions   1058 non-null   object
dtypes: datetime64[ns](1), float64(3), object(6)
memory usage: 82.8+ KB

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions
0,1930.0,1930-07-13 15:00:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,
1,1930.0,1930-07-13 15:00:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,
2,1930.0,1930-07-14 12:45:00,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,
3,1930.0,1930-07-14 14:50:00,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,
4,1930.0,1930-07-15 16:00:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,

In [ ]:
df_mundial["Year"] = df_mundial["Year"].astype(int)
df_mundial["Home Team Goals"] = df_mundial["Home Team Goals"].astype(int)
df_mundial["Away Team Goals"] = df_mundial["Away Team Goals"].astype(int)
df_mundial.info()
df_mundial.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1058 entries, 0 to 1057
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             1058 non-null   int64
 1   Datetime         826 non-null    datetime64[ns]
 2   Stage            1058 non-null   object
 3   Stadium          1058 non-null   object
 4   City             1058 non-null   object
 5   Home Team Name   1058 non-null   object
 6   Home Team Goals  1058 non-null   int64
 7   Away Team Goals  1058 non-null   int64
 8   Away Team Name   1058 non-null   object
 9   Win conditions   1058 non-null   object
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 82.8+ KB

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions
0,1930,1930-07-13 15:00:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,
1,1930,1930-07-13 15:00:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,
2,1930,1930-07-14 12:45:00,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,
3,1930,1930-07-14 14:50:00,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,
4,1930,1930-07-15 16:00:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,

1.¿Cuales son las 6 ciudades que mas partidos han visto disputarse y cuantos partidos en cada una?

In [ ]:
sorted(df_mundial["City"].unique())

['Al Khor',
 'Al Rayyan',
 'Al Wakrah',
 'Alicante ',
 'Antibes ',
 'Arica ',
 'Arlington',
 'Atlanta',
 'Barcelona ',
 'Bari ',
 'Basel ',
 'Belo Horizonte ',
 'Berlin ',
 'Berlin West ',
 'Berne ',
 'Bilbao ',
 'Birmingham ',
 'Bologna ',
 'Boras ',
 'Bordeaux ',
 'Boston',
 'Boston ',
 'Brasilia ',
 'Buenos Aires ',
 'Busan ',
 'Cagliari ',
 'Cape Town ',
 'Chicago ',
 'Cologne ',
 'Colombes ',
 'Cordoba ',
 'Cuiaba ',
 'Curitiba ',
 'Daegu ',
 'Daejeon ',
 'Dallas',
 'Dallas ',
 'Detroit ',
 'Doha',
 'Dortmund ',
 'Durban ',
 'D�Sseldorf ',
 'Elche ',
 'Eskilstuna ',
 'Florence ',
 'Fortaleza ',
 'Foxborough',
 'Frankfurt/Main ',
 'Gelsenkirchen ',
 'Geneva ',
 'Genoa ',
 'Gijon ',
 'Gothenburg ',
 'Guadalajara',
 'Guadalajara ',
 'Gwangju ',
 'Halmstad ',
 'Hamburg ',
 'Hanover ',
 'Helsingborg ',
 'Houston',
 'Ibaraki ',
 'Incheon ',
 'Irapuato ',
 'Jeju ',
 'Jeonju ',
 'Johannesburg ',
 'Kaiserslautern ',
 'Kaliningrad',
 'Kansas City',
 'Kazan',
 'Kobe ',
 'La Coru�A ',
 'Lausanne ',
 'Le Havre ',
 'Leipzig ',
 'Lens ',
 'Leon ',
 'Lille ',
 'Liverpool ',
 'London ',
 'Los Angeles',
 'Los Angeles ',
 'Lugano ',
 'Lusail',
 'Lyon ',
 'Madrid ',
 'Malaga ',
 'Malm� ',
 'Manaus ',
 'Manchester ',
 'Mangaung/Bloemfontein ',
 'Mar Del Plata ',
 'Marseilles ',
 'Mendoza ',
 'Mexico City',
 'Mexico City ',
 'Miami',
 'Middlesbrough ',
 'Milan ',
 'Monterrey',
 'Monterrey ',
 'Montevideo ',
 'Montpellier ',
 'Moscow',
 'Munich ',
 'Nantes ',
 'Naples ',
 'Natal ',
 'Nelson Mandela Bay/Port Elizabeth ',
 'Nelspruit ',
 'New Jersey',
 'New York/New Jersey ',
 'Nezahualcoyotl ',
 'Niigata ',
 'Nizhny Novgorod',
 'Norrk�Ping ',
 'Nuremberg ',
 'Oita ',
 'Orebro ',
 'Orlando ',
 'Osaka ',
 'Oviedo ',
 'Palermo ',
 'Paris ',
 'Philadelphia',
 'Phokeng ',
 'Polokwane ',
 'Porto Alegre ',
 'Puebla ',
 'Queretaro ',
 'Rancagua ',
 'Recife ',
 'Reims ',
 'Rifu ',
 'Rio De Janeiro ',
 'Rome ',
 'Rosario ',
 'Rostov-on-Don',
 'Saint Petersburg',
 'Saint-Denis ',
 'Saint-Etienne ',
 'Saitama ',
 'Salvador ',
 'Samara',
 'San Francisco',
 'San Francisco ',
 'Sandviken ',
 'Santa Clara',
 'Santiago De Chile ',
 'Sao Paulo ',
 'Sapporo ',
 'Saransk',
 'Seattle',
 'Seoul ',
 'Seville ',
 'Sheffield ',
 'Shizuoka ',
 'Sochi',
 'Solna ',
 'Strasbourg ',
 'Stuttgart ',
 'Sunderland ',
 'Suwon ',
 'Toluca ',
 'Toronto',
 'Toulouse ',
 'Trieste ',
 'Tshwane/Pretoria ',
 'Turin ',
 'Udevalla ',
 'Udine ',
 'Ulsan ',
 'Valencia ',
 'Valladolid ',
 'Vancouver',
 'Vasteras ',
 'Verona ',
 'Vigo ',
 'Vina Del Mar ',
 'Volgograd',
 'Washington Dc ',
 'Yekaterinburg',
 'Yokohama ',
 'Zapopan',
 'Zaragoza ',
 'Zurich ']

In [ ]:
df_mundial["City"] = df_mundial["City"].str.strip()
Reemplazos_ciudades = {"Berlin West":"Berlin",
              "New York/New Jersey":"New Jersey"}
df_mundial["City"] = df_mundial["City"].replace(Reemplazos_ciudades)
sorted(df_mundial["City"].unique())

['Al Khor',
 'Al Rayyan',
 'Al Wakrah',
 'Alicante',
 'Antibes',
 'Arica',
 'Arlington',
 'Atlanta',
 'Barcelona',
 'Bari',
 'Basel',
 'Belo Horizonte',
 'Berlin',
 'Berne',
 'Bilbao',
 'Birmingham',
 'Bologna',
 'Boras',
 'Bordeaux',
 'Boston',
 'Brasilia',
 'Buenos Aires',
 'Busan',
 'Cagliari',
 'Cape Town',
 'Chicago',
 'Cologne',
 'Colombes',
 'Cordoba',
 'Cuiaba',
 'Curitiba',
 'Daegu',
 'Daejeon',
 'Dallas',
 'Detroit',
 'Doha',
 'Dortmund',
 'Durban',
 'D�Sseldorf',
 'Elche',
 'Eskilstuna',
 'Florence',
 'Fortaleza',
 'Foxborough',
 'Frankfurt/Main',
 'Gelsenkirchen',
 'Geneva',
 'Genoa',
 'Gijon',
 'Gothenburg',
 'Guadalajara',
 'Gwangju',
 'Halmstad',
 'Hamburg',
 'Hanover',
 'Helsingborg',
 'Houston',
 'Ibaraki',
 'Incheon',
 'Irapuato',
 'Jeju',
 'Jeonju',
 'Johannesburg',
 'Kaiserslautern',
 'Kaliningrad',
 'Kansas City',
 'Kazan',
 'Kobe',
 'La Coru�A',
 'Lausanne',
 'Le Havre',
 'Leipzig',
 'Lens',
 'Leon',
 'Lille',
 'Liverpool',
 'London',
 'Los Angeles',
 'Lugano',
 'Lusail',
 'Lyon',
 'Madrid',
 'Malaga',
 'Malm�',
 'Manaus',
 'Manchester',
 'Mangaung/Bloemfontein',
 'Mar Del Plata',
 'Marseilles',
 'Mendoza',
 'Mexico City',
 'Miami',
 'Middlesbrough',
 'Milan',
 'Monterrey',
 'Montevideo',
 'Montpellier',
 'Moscow',
 'Munich',
 'Nantes',
 'Naples',
 'Natal',
 'Nelson Mandela Bay/Port Elizabeth',
 'Nelspruit',
 'New Jersey',
 'Nezahualcoyotl',
 'Niigata',
 'Nizhny Novgorod',
 'Norrk�Ping',
 'Nuremberg',
 'Oita',
 'Orebro',
 'Orlando',
 'Osaka',
 'Oviedo',
 'Palermo',
 'Paris',
 'Philadelphia',
 'Phokeng',
 'Polokwane',
 'Porto Alegre',
 'Puebla',
 'Queretaro',
 'Rancagua',
 'Recife',
 'Reims',
 'Rifu',
 'Rio De Janeiro',
 'Rome',
 'Rosario',
 'Rostov-on-Don',
 'Saint Petersburg',
 'Saint-Denis',
 'Saint-Etienne',
 'Saitama',
 'Salvador',
 'Samara',
 'San Francisco',
 'Sandviken',
 'Santa Clara',
 'Santiago De Chile',
 'Sao Paulo',
 'Sapporo',
 'Saransk',
 'Seattle',
 'Seoul',
 'Seville',
 'Sheffield',
 'Shizuoka',
 'Sochi',
 'Solna',
 'Strasbourg',
 'Stuttgart',
 'Sunderland',
 'Suwon',
 'Toluca',
 'Toronto',
 'Toulouse',
 'Trieste',
 'Tshwane/Pretoria',
 'Turin',
 'Udevalla',
 'Udine',
 'Ulsan',
 'Valencia',
 'Valladolid',
 'Vancouver',
 'Vasteras',
 'Verona',
 'Vigo',
 'Vina Del Mar',
 'Volgograd',
 'Washington Dc',
 'Yekaterinburg',
 'Yokohama',
 'Zapopan',
 'Zaragoza',
 'Zurich']

In [ ]:
ciudades = pd.DataFrame(df_mundial["City"].value_counts())
ciudades.head(6)

              count
City
Mexico City      27
Al Rayyan        23
Guadalajara      21
Montevideo       18
Los Angeles      16
Johannesburg     15

# las ciudades que mas partidos han albergado de copas mundiales son ciudad de mexico, al rayyan, guadalajara, montevideo, los angeles y johannesburgo.

2.¿Cuales son los 3 paises que mas partidos a jugado en los mundiales?

In [ ]:
sorted(df_mundial["Home Team Name"].unique())

['Algeria',
 'Angola',
 'Argentina',
 'Australia',
 'Austria',
 'Belgium',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Brazil',
 'Bulgaria',
 'Cabo Verde',
 'Cameroon',
 'Canada',
 'Chile',
 'China PR',
 'Colombia',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Curaçao',
 'Czech Republic',
 'Czechia',
 'Czechoslovakia',
 "Côte d'Ivoire",
 "C�te d'Ivoire",
 'Denmark',
 'Ecuador',
 'Egypt',
 'England',
 'France',
 'German DR',
 'Germany',
 'Germany FR',
 'Ghana',
 'Greece',
 'Haiti',
 'Honduras',
 'Hungary',
 'IR Iran',
 'Iceland',
 'Iran',
 'Iraq',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Korea DPR',
 'Korea Republic',
 'Mexico',
 'Morocco',
 'Netherlands',
 'New Zealand',
 'Nigeria',
 'Northern Ireland',
 'Norway',
 'Panama',
 'Paraguay',
 'Peru',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Saudi Arabia',
 'Scotland',
 'Senegal',
 'Serbia',
 'Slovakia',
 'Slovenia',
 'South Africa',
 'South Korea',
 'Soviet Union',
 'Spain',
 'Sweden',
 'Switzerland',
 'Togo',
 'Tunisia',
 'Turkey',
 'Türkiye',
 'USA',
 'Ukraine',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Wales',
 'Yugoslavia',
 'Zaire',
 'rn">Bosnia and Herzegovina',
 'rn">Republic of Ireland',
 'rn">Serbia and Montenegro',
 'rn">Trinidad and Tobago',
 'rn">United Arab Emirates']

In [ ]:
Reemplazos_paises = {"Czech Republic":"Czechia",
              "Côte d'Ivoire":"C\u00f4te d'Ivoire",
              "Ivory Coast":"C\u00f4te d'Ivoire",
              "German DR":"Germany",
              "Germany FR":"Germany",
              "IR Iran":"Iran",
              "Korea DPR":"Korea Republic",
              "Türkiye":"Turkey",
              "USA":"United States",
              "rn\">Bosnia and Herzegovina":"Bosnia and Herzegovina",
              "rn\">Republic of Ireland":"Republic of Ireland",
              "rn\">Serbia and Montenegro":"Serbia and Montenegro",
              "rn\">Trinidad and Tobago":"Trinidad and Tobago",
              "rn\">United Arab Emirates":"United Arab Emirates",
              "Soviet Union":"Russia"}

In [ ]:
df_mundial["Home Team Name"] = df_mundial["Home Team Name"].str.strip()
df_mundial["Home Team Name"] = df_mundial["Home Team Name"].replace(Reemplazos_paises)

sorted(df_mundial["Home Team Name"].unique())

['Algeria',
 'Angola',
 'Argentina',
 'Australia',
 'Austria',
 'Belgium',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Brazil',
 'Bulgaria',
 'Cabo Verde',
 'Cameroon',
 'Canada',
 'Chile',
 'China PR',
 'Colombia',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Curaçao',
 'Czechia',
 'Czechoslovakia',
 "Côte d'Ivoire",
 "C�te d'Ivoire",
 'Denmark',
 'Ecuador',
 'Egypt',
 'England',
 'France',
 'Germany',
 'Ghana',
 'Greece',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'Iran',
 'Iraq',
 'Italy',
 'Jamaica',
 'Japan',
 'Korea Republic',
 'Mexico',
 'Morocco',
 'Netherlands',
 'New Zealand',
 'Nigeria',
 'Northern Ireland',
 'Norway',
 'Panama',
 'Paraguay',
 'Peru',
 'Poland',
 'Portugal',
 'Qatar',
 'Republic of Ireland',
 'Romania',
 'Russia',
 'Saudi Arabia',
 'Scotland',
 'Senegal',
 'Serbia',
 'Serbia and Montenegro',
 'Slovakia',
 'Slovenia',
 'South Africa',
 'South Korea',
 'Spain',
 'Sweden',
 'Switzerland',
 'Togo',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Ukraine',
 'United Arab Emirates',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Wales',
 'Yugoslavia',
 'Zaire']

In [ ]:
sorted(df_mundial["Away Team Name"].unique())

['Algeria',
 'Angola',
 'Argentina',
 'Australia',
 'Austria',
 'Belgium',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Brazil',
 'Bulgaria',
 'Cabo Verde',
 'Cameroon',
 'Canada',
 'Chile',
 'China PR',
 'Colombia',
 'Congo DR',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Curaçao',
 'Czech Republic',
 'Czechia',
 'Czechoslovakia',
 "C�te d'Ivoire",
 'Denmark',
 'Dutch East Indies',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'England',
 'France',
 'German DR',
 'Germany',
 'Germany FR',
 'Ghana',
 'Greece',
 'Haiti',
 'Honduras',
 'Hungary',
 'IR Iran',
 'Iceland',
 'Iran',
 'Iraq',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Korea DPR',
 'Korea Republic',
 'Kuwait',
 'Mexico',
 'Morocco',
 'Netherlands',
 'New Zealand',
 'Nigeria',
 'Northern Ireland',
 'Norway',
 'Panama',
 'Paraguay',
 'Peru',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Saudi Arabia',
 'Scotland',
 'Senegal',
 'Serbia',
 'Slovakia',
 'Slovenia',
 'South Africa',
 'South Korea',
 'Soviet Union',
 'Spain',
 'Sweden',
 'Switzerland',
 'Togo',
 'Tunisia',
 'Turkey',
 'Türkiye',
 'USA',
 'Ukraine',
 'United States',
 'Uruguay',
 'Wales',
 'Yugoslavia',
 'Zaire',
 'rn">Bosnia and Herzegovina',
 'rn">Republic of Ireland',
 'rn">Serbia and Montenegro',
 'rn">Trinidad and Tobago',
 'rn">United Arab Emirates']

In [ ]:
df_mundial["Away Team Name"] = df_mundial["Away Team Name"].str.strip()
df_mundial["Away Team Name"] = df_mundial["Away Team Name"].replace(Reemplazos_paises)

sorted(df_mundial["Away Team Name"].unique())

['Algeria',
 'Angola',
 'Argentina',
 'Australia',
 'Austria',
 'Belgium',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Brazil',
 'Bulgaria',
 'Cabo Verde',
 'Cameroon',
 'Canada',
 'Chile',
 'China PR',
 'Colombia',
 'Congo DR',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Curaçao',
 'Czechia',
 'Czechoslovakia',
 "Côte d'Ivoire",
 "C�te d'Ivoire",
 'Denmark',
 'Dutch East Indies',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'England',
 'France',
 'Germany',
 'Ghana',
 'Greece',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'Iran',
 'Iraq',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Korea Republic',
 'Kuwait',
 'Mexico',
 'Morocco',
 'Netherlands',
 'New Zealand',
 'Nigeria',
 'Northern Ireland',
 'Norway',
 'Panama',
 'Paraguay',
 'Peru',
 'Poland',
 'Portugal',
 'Qatar',
 'Republic of Ireland',
 'Romania',
 'Russia',
 'Saudi Arabia',
 'Scotland',
 'Senegal',
 'Serbia',
 'Serbia and Montenegro',
 'Slovakia',
 'Slovenia',
 'South Africa',
 'South Korea',
 'Spain',
 'Sweden',
 'Switzerland',
 'Togo',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Ukraine',
 'United Arab Emirates',
 'United States',
 'Uruguay',
 'Wales',
 'Yugoslavia',
 'Zaire']

In [ ]:
df_paises = pd.concat([df_mundial["Home Team Name"], df_mundial["Away Team Name"]])
df_paises.value_counts().head(3)

Germany      122
Brazil       119
Argentina     94
Name: count, dtype: int64

# los paises que màs partidos han jugado en los mundiales son alemania, brasil y argentina

3.¿Que pais ha jugado mas finales sin ganarlas?

In [ ]:
sorted(df_mundial["Stage"].unique())

['Final',
 'Finals',
 'First round',
 'Group 1',
 'Group 2',
 'Group 3',
 'Group 4',
 'Group 5',
 'Group 6',
 'Group A',
 'Group B',
 'Group C',
 'Group D',
 'Group E',
 'Group F',
 'Group G',
 'Group H',
 'Group Stage',
 'Match for third place',
 'Play-off for third place',
 'Preliminary round',
 'Quarter-finals',
 'Round of 16',
 'Round of 32',
 'Semi-finals',
 'Third Place',
 'Third place',
 'final',
 'group stage',
 'quarter-finals',
 'round of 16',
 'semi-finals',
 'third-place match']

In [ ]:
df_mundial["Stage"] = df_mundial["Stage"].str.strip()
Reemplazos_finales = {"Finals":"Final", "final":"Final"}
df_mundial["Stage"] = df_mundial["Stage"].replace(Reemplazos_finales)
sorted(df_mundial["Stage"].unique())

['Final',
 'First round',
 'Group 1',
 'Group 2',
 'Group 3',
 'Group 4',
 'Group 5',
 'Group 6',
 'Group A',
 'Group B',
 'Group C',
 'Group D',
 'Group E',
 'Group F',
 'Group G',
 'Group H',
 'Group Stage',
 'Match for third place',
 'Play-off for third place',
 'Preliminary round',
 'Quarter-finals',
 'Round of 16',
 'Round of 32',
 'Semi-finals',
 'Third Place',
 'Third place',
 'group stage',
 'quarter-finals',
 'round of 16',
 'semi-finals',
 'third-place match']

In [ ]:
df_finalistas = df_mundial[df_mundial['Stage'] == "Final"]
df_finalistas

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions
17,1930,1930-07-30 14:15:00,Final,Estadio Centenario,Montevideo,Uruguay,4,2,Argentina,
34,1934,1934-06-10 17:30:00,Final,Nazionale PNF,Rome,Italy,2,1,Czechoslovakia,Italy win after extra time
52,1938,1938-06-19 17:00:00,Final,Stade Olympique,Colombes,Italy,4,2,Hungary,
100,1954,1954-07-04 17:00:00,Final,Wankdorf Stadium,Berne,Germany,3,2,Hungary,
135,1958,1958-06-29 15:00:00,Final,Rasunda Stadium,Solna,Brazil,5,2,Sweden,
167,1962,1962-06-17 14:30:00,Final,Nacional,Santiago De Chile,Brazil,3,1,Czechoslovakia,
199,1966,1966-07-30 15:00:00,Final,Wembley Stadium,London,England,4,2,Germany,England win after extra time
231,1970,1970-06-21 12:00:00,Final,Estadio Azteca,Mexico City,Brazil,4,1,Italy,
269,1974,NaT,Final,Olympiastadion,Munich,Netherlands,1,2,Germany,
307,1978,1978-06-25 15:00:00,Final,El Monumental - Estadio Monumental Antonio Ves...,Buenos Aires,Argentina,3,1,Netherlands,Argentina win after extra time
359,1982,1982-07-11 20:00:00,Final,Santiago Bernabeu,Madrid,Italy,3,1,Germany,
411,1986,1986-06-29 12:00:00,Final,Estadio Azteca,Mexico City,Argentina,3,2,Germany,
463,1990,1990-07-08 20:00:00,Final,Stadio Olimpico,Rome,Germany,1,0,Argentina,
515,1994,1994-07-17 12:30:00,Final,Rose Bowl,Los Angeles,Brazil,0,0,Italy,Brazil win on penalties (3 - 2)
579,1998,1998-07-12 21:00:00,Final,Stade de France,Saint-Denis,Brazil,0,3,France,
643,2002,2002-06-30 20:00:00,Final,International Stadium Yokohama,Yokohama,Germany,0,2,Brazil,
707,2006,2006-07-09 20:00:00,Final,Olympiastadion,Berlin,Italy,1,1,France,Italy win on penalties (5 - 3)
771,2010,2010-07-11 20:30:00,Final,Soccer City Stadium,Johannesburg,Netherlands,0,1,Spain,Spain win after extra time
828,2014,2014-07-13 16:00:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,Germany win after extra time
899,2018,NaT,Final,Luzhniki Stadium,Moscow,France,4,2,Croatia,
963,2022,NaT,Final,Lusail Stadium,Lusail,Argentina,3,3,France,Argentina win on penalties (4 - 2)
1057,2026,NaT,Final,New York New Jersey Stadium,New Jersey,Spain,1,0,Argentina,Spain win after extra time

In [ ]:
df_finalistas_locales_perdedores = df_finalistas["Home Team Goals"] < df_finalistas["Away Team Goals"]
df_finalistas_locales_perdedores

17      False
34      False
52      False
100     False
135     False
167     False
199     False
231     False
269      True
307     False
359     False
411     False
463     False
515     False
579      True
643      True
707     False
771      True
828     False
899     False
963     False
1057    False
dtype: bool

In [ ]:
df_finalistas_visitantes_perdedores = df_finalistas["Away Team Goals"] < df_finalistas["Home Team Goals"]
df_finalistas_visitantes_perdedores

17       True
34       True
52       True
100      True
135      True
167      True
199      True
231      True
269     False
307      True
359      True
411      True
463      True
515     False
579     False
643     False
707     False
771     False
828      True
899      True
963     False
1057     True
dtype: bool

In [ ]:
df_equipos_locales_perdedores = df_finalistas[df_finalistas_locales_perdedores]['Home Team Name']
df_equipos_locales_perdedores

269    Netherlands
579         Brazil
643        Germany
771    Netherlands
Name: Home Team Name, dtype: object

In [ ]:
df_equipos_visitantes_perdedores = df_finalistas[df_finalistas_visitantes_perdedores]['Away Team Name']
df_equipos_visitantes_perdedores

17           Argentina
34      Czechoslovakia
52             Hungary
100            Hungary
135             Sweden
167     Czechoslovakia
199            Germany
231              Italy
307        Netherlands
359            Germany
411            Germany
463          Argentina
828          Argentina
899            Croatia
1057         Argentina
Name: Away Team Name, dtype: object

In [ ]:
df_finalistas_perdedores = pd.concat([df_equipos_locales_perdedores, df_equipos_visitantes_perdedores])
df_finalistas_perdedores.value_counts()

Germany           4
Argentina         4
Netherlands       3
Czechoslovakia    2
Hungary           2
Brazil            1
Sweden            1
Italy             1
Croatia           1
Name: count, dtype: int64

# Los paises que mas finales han perdido son Alemania y argentina.